# Kind cluster configuration for Felicia's Finance development
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: felicias-finance

# Cluster-wide configuration
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  # Pod subnet CIDR
  podSubnet: "10.244.0.0/16"
  # Service subnet CIDR
  serviceSubnet: "10.96.0.0/16"

# Nodes configuration
nodes:
# Control plane node
- role: control-plane
  image: kindest/node:v1.27.3
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Expose ingress controller
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # Expose API server
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
  # Expose orchestrator
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  # Expose banking agent
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  # Expose crypto agent
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP

# Worker nodes
- role: worker
  image: kindest/node:v1.27.3
  extraMounts:
  - hostPath: /tmp/felicias-finance
    containerPath: /tmp/felicias-finance
    readOnly: false
    selinuxRelabel: false
    propagation: None

- role: worker
  image: kindest/node:v1.27.3
  extraMounts:
  - hostPath: /tmp/felicias-finance
    containerPath: /tmp/felicias-finance
    readOnly: false
    selinuxRelabel: false
    propagation: None

# Feature gates and runtime configuration
featureGates:
  # Enable feature gates as needed
  EphemeralContainers: true

# Kubernetes version and configuration
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
  etcd:
    local:
      extraArgs:
        listen-metrics-urls: http://0.0.0.0:2381
- |
  kind: KubeProxyConfiguration
  metricsBindAddress: 0.0.0.0:10249
